import { afterEach, describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, symlinkSync, utimesSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join } from "node:path";

import { candidates, findTranscript, openingPrompt } from "../plugins/pstack/skills/reflect/scripts/find-transcript.mjs";
import { removeDuring } from "./remove-during.mjs";

const script = join(import.meta.dir, "../plugins/pstack/skills/reflect/scripts/find-transcript.mjs");
const noNode = spawnSync("node", ["--version"]).status !== 0;

const meta = JSON.stringify({ type: "bridge-session", sessionId: "abc" });
const summary = JSON.stringify({ type: "summary", summary: "earlier work" });
const user = (text) => JSON.stringify({ type: "user", message: { role: "user", content: [{ type: "text", text }] } });
const userString = (text) => JSON.stringify({ type: "user", message: { role: "user", content: text } });
const assistant = JSON.stringify({ type: "assistant", message: { role: "assistant", content: [{ type: "text", text: "ok" }] } });

const fixtures = [];
afterEach(() => {
  for (const root of fixtures.splice(0)) rmSync(root, { recursive: true, force: true });
});

function tempDir() {
  const dir = mkdtempSync(join(tmpdir(), "reflect-"));
  fixtures.push(dir);
  return dir;
}

function transcript(dir, rel, lines, mtimeSeconds) {
  const path = join(dir, rel);
  mkdirSync(join(path, ".."), { recursive: true });
  writeFileSync(path, `${lines.join("\n")}\n`);
  utimesSync(path, mtimeSeconds, mtimeSeconds);
  return path;
}

describe("find-transcript", () => {
  test("the opening prompt is the first user record, not the first line", async () => {
    const dir = tempDir();
    const path = transcript(dir, "a.jsonl", [meta, summary, assistant, user("fix the flaky login test")], 100);
    expect(await openingPrompt(path)).toBe("fix the flaky login test");
  });

  test("string content and multi-block content both yield the prompt text", async () => {
    const dir = tempDir();
    const plain = transcript(dir, "plain.jsonl", [meta, userString("plain prompt")], 100);
    const blocks = transcript(
      dir,
      "blocks.jsonl",
      [meta, JSON.stringify({ type: "user", message: { content: [{ type: "text", text: "<reminder/>" }, { type: "text", text: "real prompt" }] } })],
      100,
    );
    expect(await openingPrompt(plain)).toBe("plain prompt");
    expect(await openingPrompt(blocks)).toContain("real prompt");
  });

  test("meta and command records before the typed prompt are skipped", async () => {
    const dir = tempDir();
    const caveat = JSON.stringify({ type: "user", isMeta: true, message: { content: "Caveat: the messages below were generated by local commands" } });
    const command = userString("<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>");
    const stdout = userString("<local-command-stdout></local-command-stdout>");
    const shell = userString("<bash-input>git status</bash-input><bash-stdout>clean</bash-stdout>");
    const path = transcript(dir, "cleared.jsonl", [meta, caveat, command, stdout, shell, user("review the release lanes")], 100);
    expect(await openingPrompt(path)).toBe("review the release lanes");
  });

  test("a skill invocation is the typed prompt and keeps its arguments", async () => {
    const dir = tempDir();
    const skill = userString("<command-message>pstack:reflect</command-message>\n<command-name>/pstack:reflect</command-name>\n<command-args>the release lanes</command-args>");
    const path = transcript(dir, "skill.jsonl", [meta, skill, user("a later prompt")], 100);
    expect(await openingPrompt(path)).toContain("the release lanes");
  });

  test("a transcript with no user record has no opening prompt", async () => {
    const dir = tempDir();
    const path = transcript(dir, "meta-only.jsonl", [meta, summary], 100);
    expect(await openingPrompt(path)).toBeNull();
  });

  test("candidates cover flat, nested, and subagent layouts, newest first", () => {
    const dir = tempDir();
    const flat = transcript(dir, "flat.jsonl", [meta], 100);
    const nested = transcript(dir, "n1/n1.jsonl", [meta], 300);
    const sub = transcript(dir, "n1/subagents/child.jsonl", [meta], 200);
    writeFileSync(join(dir, "notes.txt"), "not a transcript");
    expect(candidates(dir).map(({ path }) => path)).toEqual([nested, sub, flat]);
  });

  test("findTranscript returns the newest transcript whose opening prompt carries the fragment", async () => {
    const dir = tempDir();
    transcript(dir, "old.jsonl", [meta, user("review issue 59")], 100);
    const newer = transcript(dir, "new/new.jsonl", [meta, user("review issue 59 and related points")], 200);
    transcript(dir, "other.jsonl", [meta, user("unrelated")], 300);
    expect(await findTranscript(dir, "issue 59")).toBe(newer);
    expect(await findTranscript(dir, "nothing matches this")).toBeNull();
  });

  test("a transcript deleted after enumeration does not abort the scan", async () => {
    const dir = tempDir();
    transcript(dir, "newest.jsonl", [meta, user("unrelated prompt")], 300);
    const removed = transcript(dir, "removed.jsonl", [meta, user("another prompt")], 200);
    const older = transcript(dir, "older.jsonl", [meta, user("resume the audit")], 100);
    const search = findTranscript(dir, "resume the audit");
    // Enumeration has completed; the first streamed read yields before this candidate opens.
    rmSync(removed);
    expect(await search).toBe(older);
  });

  test.skipIf(noNode)(
    "a session directory or transcript removed while the tree is listed is skipped (skipped without node)",
    () => {
      const dir = tempDir();
      const kept = transcript(dir, "kept.jsonl", [meta], 100);
      const flat = transcript(dir, "flat.jsonl", [meta], 200);
      transcript(dir, "s1/s1.jsonl", [meta], 300);
      const body = `const { candidates } = await import(${JSON.stringify(script)});
        console.log(JSON.stringify(candidates(${JSON.stringify(dir)}).map(({ path }) => path)));`;
      const run = removeDuring("readdirSync", dir, [join(dir, "s1"), flat], body);
      expect(run.stderr).toBe("");
      expect(JSON.parse(run.stdout)).toEqual([kept]);
    },
  );

  test("other candidate read errors still propagate", async () => {
    const dir = tempDir();
    transcript(dir, "newest.jsonl", [meta, user("unrelated prompt")], 300);
    const changed = transcript(dir, "changed.jsonl", [meta], 200);
    const search = findTranscript(dir, "audit");
    rmSync(changed);
    mkdirSync(changed);
    await expect(search).rejects.toMatchObject({ code: "EISDIR" });
  });

  test("a missing project directory still reports the filesystem error", async () => {
    await expect(findTranscript(join(tempDir(), "missing"), "audit")).rejects.toMatchObject({ code: "ENOENT" });
  });

  test("a truncated trailing line does not abort the scan", async () => {
    const dir = tempDir();
    const live = join(dir, "live.jsonl");
    writeFileSync(live, `${meta}\n{"type":"us`);
    utimesSync(live, 200, 200);
    const older = transcript(dir, "older.jsonl", [meta, user("resume the audit")], 100);
    expect(await openingPrompt(live)).toBeNull();
    expect(await findTranscript(dir, "resume the audit")).toBe(older);
  });

  // Pi's layout: <sessions>/--<cwd>--/<iso>_<uuid>.jsonl, a header line, then
  // entries linked by id/parentId; branching appends to the same file.
  const piHeader = JSON.stringify({ type: "session", version: 3, id: "s-1", timestamp: "2026-10-01T00:00:00.000Z", cwd: "/work/repo" });
  const piEntry = (id, parentId, type, fields = {}) =>
    JSON.stringify({ type, id, parentId, timestamp: "2026-10-01T00:00:01.000Z", ...fields });
  const piMessage = (id, parentId, role, text) =>
    piEntry(id, parentId, "message", { message: { role, content: [{ type: "text", text }], timestamp: 1 } });

  test("a Pi session's opening prompt is the first user message on the branch that ends at the last entry", async () => {
    const dir = tempDir();
    const path = transcript(
      dir,
      "--work-repo--/2026-10-01T00-00-00-000Z_s-1.jsonl",
      [
        piHeader,
        piMessage("sys", null, "system", "You are Pi."),
        piMessage("u1", "sys", "user", "abandoned opening"),
        piMessage("a1", "u1", "assistant", "ok"),
        piEntry("sum", "sys", "branch_summary", { fromId: "a1", summary: "tried A" }),
        piMessage("u2", "sum", "user", "ship the release lanes"),
        piMessage("a2", "u2", "assistant", "on it"),
        piMessage("t2", "a2", "toolResult", "done"),
        piMessage("u3", "t2", "user", "a later prompt"),
      ],
      100,
    );
    expect(await openingPrompt(path)).toBe("ship the release lanes");
  });

  test("a Pi session whose leaf is on the first branch keeps that branch's opening", async () => {
    const dir = tempDir();
    const path = transcript(
      dir,
      "--work-repo--/s.jsonl",
      [
        piHeader,
        piMessage("u1", null, "user", "first branch opening"),
        piMessage("a1", "u1", "assistant", "ok"),
        piMessage("u2", null, "user", "second root opening"),
        piEntry("c1", "a1", "custom", { customType: "pstack-agents", data: {} }),
      ],
      100,
    );
    expect(await openingPrompt(path)).toBe("first branch opening");
  });

  test("a raw U+2028 or U+2029 inside a record does not split it", async () => {
    const dir = tempDir();
    const claude = transcript(dir, "c.jsonl", [meta, user("fix the parser\u2028please"), user("a later prompt")], 100);
    const pi = transcript(
      dir,
      "--work-repo--/s.jsonl",
      [piHeader, piMessage("u1", null, "user", "ship the release"), piMessage("a1", "u1", "assistant", "line\u2029break"), piMessage("u2", "a1", "user", "a later prompt")],
      100,
    );
    expect(await openingPrompt(claude)).toBe("fix the parser\u2028please");
    expect(await openingPrompt(pi)).toBe("ship the release");
  });

  test("a Pi session with no user message on its active branch has no opening prompt", async () => {
    const dir = tempDir();
    const path = transcript(
      dir,
      "--work-repo--/s.jsonl",
      [piHeader, piMessage("u1", null, "user", "dead"), piEntry("m", null, "model_change", { provider: "p", modelId: "m" })],
      100,
    );
    expect(await openingPrompt(path)).toBeNull();
  });

  test("findTranscript finds a Pi session among Claude transcripts in the same tree", async () => {
    const dir = tempDir();
    transcript(dir, "claude.jsonl", [meta, user("review issue 59")], 100);
    const pi = transcript(dir, "--work-repo--/s.jsonl", [piHeader, piMessage("u1", null, "user", "review issue 59 on Pi")], 200);
    expect(await findTranscript(dir, "on Pi")).toBe(pi);
    expect(await findTranscript(dir, "issue 59")).toBe(pi);
  });

  // Copilot's layout: <session-state>/<id>/events.jsonl, a session.start event,
  // then one event per line with each typed prompt as a user.message.
  const copilotStart = JSON.stringify({ type: "session.start", data: { sessionId: "c1", context: { cwd: process.cwd() } } });
  const copilotEvent = (type, content) => JSON.stringify({ type, data: { content } });

  test("a Copilot session's opening prompt is its first user.message, not the injected context", async () => {
    const dir = tempDir();
    const path = transcript(dir, "c1/events.jsonl", [
      copilotStart,
      copilotEvent("hook.end", "routing context"),
      copilotEvent("user.message", ""),
      copilotEvent("user.message", "review issue 59 on Copilot"),
      copilotEvent("user.message", "a later prompt"),
    ], 100);
    expect(await openingPrompt(path)).toBe("review issue 59 on Copilot");
  });

  test("findTranscript finds a Copilot session among Claude transcripts in the same tree", async () => {
    const dir = tempDir();
    transcript(dir, "claude.jsonl", [meta, user("review issue 59")], 100);
    const copilot = transcript(dir, "c1/events.jsonl", [copilotStart, copilotEvent("user.message", "review issue 59 on Copilot")], 200);
    expect(await findTranscript(dir, "on Copilot")).toBe(copilot);
  });

  test.skipIf(noNode)("the CLI scopes Copilot sessions to the workspace when opening prompts match", () => {
    const dir = tempDir();
    const sessions = join(dir, "session-state");
    const workspace = join(dir, "work");
    const unrelated = join(dir, "private");
    mkdirSync(workspace);
    mkdirSync(unrelated);
    const start = (cwd) => JSON.stringify({ type: "session.start", data: { context: { cwd } } });
    const prompt = copilotEvent("user.message", "fix the failing tests");
    const current = transcript(sessions, "current/events.jsonl", [start(workspace), prompt], 100);
    transcript(sessions, "unrelated/events.jsonl", [start(unrelated), prompt], 200);
    transcript(sessions, "missing-cwd/events.jsonl", [start(undefined), prompt], 300);
    transcript(sessions, "deleted-workspace/events.jsonl", [start(join(dir, "deleted")), prompt], 400);

    const run = (cwd, args = []) => spawnSync("node", [script, sessions, "fix the failing tests", ...args], { cwd, encoding: "utf8" });
    const hit = run(workspace);
    expect(hit.status).toBe(0);
    expect(hit.stdout.trim()).toBe(current);
    const explicit = run(unrelated, [workspace]);
    expect(explicit.status).toBe(0);
    expect(explicit.stdout.trim()).toBe(current);
    const link = join(dir, "linked-work");
    symlinkSync(workspace, link);
    const alias = run(unrelated, [link]);
    expect(alias.status).toBe(0);
    expect(alias.stdout.trim()).toBe(current);
    rmSync(current);
    const miss = run(workspace);
    expect(miss.status).toBe(1);
    expect(miss.stdout).toBe("");
    expect(miss.stderr).toContain("no transcript");
  });

  test("a Codex rollout is refused by name instead of read as an empty Claude transcript", async () => {
    const dir = tempDir();
    const rollout = transcript(
      dir,
      "rollout.jsonl",
      [
        JSON.stringify({ type: "session_meta", payload: { id: "r-1", cwd: "/work/repo" } }),
        JSON.stringify({ type: "response_item", payload: { type: "message", role: "user", content: [{ type: "input_text", text: "ship the release" }] } }),
      ],
      100,
    );
    await expect(openingPrompt(rollout)).rejects.toThrow(/Codex rollout/);
    await expect(findTranscript(dir, "ship the release")).rejects.toThrow(/Codex rollout/);
  });

  test("the CLI prints the path and exits 1 when nothing matches", () => {
    const dir = tempDir();
    const path = transcript(dir, "s/s.jsonl", [meta, user("ship the release")], 100);
    const hit = spawnSync("node", [script, dir, "ship the"], { encoding: "utf8" });
    expect(hit.status).toBe(0);
    expect(hit.stdout.trim()).toBe(path);
    const miss = spawnSync("node", [script, dir, "absent"], { encoding: "utf8" });
    expect(miss.status).toBe(1);
    expect(miss.stderr).toContain("no transcript");
  });

  // node resolves the script's own URL through symlinks but not argv[1]; bun resolves both.
  test.skipIf(noNode)(
    "the CLI runs under node through a symlinked path (skipped without node)",
    () => {
      const dir = tempDir();
      const path = transcript(dir, "s/s.jsonl", [meta, user("ship the release")], 100);
      symlinkSync(dirname(script), join(dir, "link"));
      const linked = join(dir, "link", basename(script));
      const hit = spawnSync("node", [linked, dir, "ship the"], { encoding: "utf8" });
      expect(hit.status).toBe(0);
      expect(hit.stdout.trim()).toBe(path);
      const miss = spawnSync("node", [linked, dir, "absent"], { encoding: "utf8" });
      expect(miss.status).toBe(1);
      expect(miss.stderr).toContain("no transcript");
    },
  );

  test.skipIf(noNode)(
    "imports under node when argv[1] is not a file (skipped without node)",
    () => {
      const run = spawnSync(
        "node",
        ["-e", `import(${JSON.stringify(script)}).then((m) => console.log(typeof m.findTranscript))`, "not-a-file"],
        { encoding: "utf8" },
      );
      expect(run.stderr).toBe("");
      expect(run.stdout.trim()).toBe("function");
    },
  );
});
